inventory/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy 
  end

  resources :users
  resources :items
  resources :item_categories
  resources :item_edits #TODO : To remove

  get '/', to: 'items#index'
  get '/destroyed', to: 'items#destroyed'
  get '/KT/:serial', to:'items#show' #KT in english letters
  get '/RM/:serial', to:'items#show' #Rooms
  get '/I/:serial', to:'items#show' #I english letters Items
  get '/VP/:serial', to:'items#show' #I english letters Virtual Places

  get 'not_found', to: 'items#not_found'
  get 'picture', to: 'items#picture'
  get 'picture_thumb', to: 'items#picture_thumb'
  get 'second_picture', to: 'items#second_picture'
  get 'invoice', to: 'items#invoice'

  get '/upload_photo', to: 'items#upload_photo'
  post '/upload_photo', to: 'items#search_and_place_photo'

  get '/upload_invoice', to: 'items#upload_invoice'
  post '/upload_invoice', to: 'items#search_and_place_invoice'

  get '/toggle_show_all_mine', to: 'items#toggle_show_all_mine'

  get '/movements/:id', to: 'item_movements#index', as: "movements"

  get '/edits/:id', to: 'item_edits#index', as: "edits"

  get '/categories', to: 'item_categories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
 

  #----- Temporarily enabled for debugging : ( TODO )
  resources :item_photos
  resources :primary_photos
  resources :secondary_photos
  resources :invoice_photos
  #----------

end

inventory/app/models/item.rb
class Item < ApplicationRecord
  ##validates :serial, presence: true
  #
  #The serial may be hidden inside the photo, so it's ok
  #to submit without a serial
  
  belongs_to :container, optional: true, class_name: "Item"
  belongs_to :user, optional: true
  belongs_to :item_category, optional: true

  has_many :item_photos
  has_one :primary_photo
  has_one :secondary_photo
  has_one :invoice_photo

  def destroy
    self.burned = true
    self.save
  end

  def other_photos
    ItemPhoto.where(item_id: id).ids
  end

  def username(uid = @user_id)
    @username = "undef"
    @user = User.find_by(id: uid)
    if @user!=nil 
      @username = user.username
    end
    return @username
  end

  def container_serial=(serial)
    container = Item.find_by( serial: serial )
    if not container
      #second try
      container = Item.where( "lower(serial) like '%#{serial.downcase}%'" ).first
    end

    if container 
      @container = container
      update( container: @container )
    end

    if serial == "none"
      update( container: nil )
    end
  end

  def container_serial(container_id=nil)
    if container_id
      @container = Item.find( container_id )
      return @container.serial
    else
      if @container_id
        @container = Item.find( @container_id )
        return @container.serial
      end
    end
    return nil
  end


  def uploaded_picture
    self.primary_photo ? self.primary_photo.filename : nil
  end
  def uploaded_second_picture
    self.secondary_photo ? self.secondary_photo.filename : nil
  end
  def uploaded_invoice
    self.invoice_photo ? self.invoice_photo.filename : nil
  end
  def uploaded_invoice_full_path
    a = uploaded_invoice
    if a
      return File.join(ItemsController::Photos_Directory, a)
    end
  end


  #Code is heavily duplicated here and in items_controller.rb
  def uploaded_picture=(picture_field)

    if picture_field==nil
      remove_photo_file( 1 )
      return
    end

    new_filename = accept_photo_file( picture_field.tempfile )

    #Try to get the qrcode, but don't fail on that
    scanned_qr = `zbarimg #{File.absolute_path( new_filename )}`
    puts scanned_qr

    return if not scanned_qr
    
    #
    #Do the rest only if a scanned code is detected
    #

    serial_no = ""
    serial_found = false
    multiple_serials = false

    scanned_qr.lines.each do |detected_code|
      if detected_code =~ /srv-1tee-moiron\.ira\.sch\.gr/
        puts "detected inventory code : #{detected_code}"

        code_parts = detected_code.split('/')

        next if not code_parts or code_parts.length == 0
        next if not code_parts[ code_parts.length - 1]
        next if code_parts[ code_parts.length - 1].length == 0

        if serial_found
          #two codes found, user has to input the code manually
          puts "More than one code detected in the photo. User should type the right code manually"
          multiple_serials = true
          if not self.serial or self.serial.strip == ''
            serial_found = false
            raise "More than one code detected in photo"
          end
        end


        serial_no = code_parts[ code_parts.length - 1 ].strip
        if serial_no.include?("?") #there are parameters at the end
          serial_no = serial_no[0, serial_no.index("?")]
        end

        puts serial_no
        serial_found = true
      end
    end

    if serial_found
      if self.serial and self.serial.strip != ''
        puts "Already has a serial"
        if not multiple_serials and self.serial.strip != serial_no
          raise "Serial in database differs from serial in uploaded image"
        end
      else
        self.serial = serial_no
      end
    end

  end

  def uploaded_second_picture=(picture_field)

    if picture_field == nil
      remove_photo_file( 2 )
      return
    end

    accept_photo_file( picture_field.tempfile, 2 )
  end

  def uploaded_invoice=(invoice_field)

    if invoice_field == nil
      remove_photo_file( 3 )
      return
    end

    accept_photo_file( invoice_field.tempfile, 3 )
  end

  def get_immediate_contents
    a = Item.where( container_id: self.id )
  end

  def calc_sha256( tmp_file )
    sha256 = `sha256sum #{File.absolute_path(tmp_file)}`

    raise "SHA256 calculation error." if not sha256
    raise "SHA256 calculation error." if sha256.length==0
    sha256 = sha256.split()
    raise "SHA256 calculation error." if sha256.length==0
    sha256 = sha256[0]
    raise "SHA256 calculation error." if sha256.length<10

    return sha256
  end

  def get_base_filename( sha256 )
    "#{sha256}.jpg"
  end

  def get_image_filename( sha256 ) 
    base_filename = get_base_filename( sha256 )
    File.join(ItemsController::Photos_Directory, base_filename)
  end

  private

  # photo_type:
  #  1 - primary photo
  #  2 - secondary photo
  #  3 - invoice photo
  #  other - just a photo
  def accept_photo_file( tmp_file, photo_type = 1 )
    #Calculate sha256 used as the base filename
    sha256 = calc_sha256( tmp_file )
    puts sha256

    #move the uploaded file to our Photos_Directory
    uploaded_filename = File.absolute_path( tmp_file )
    stored_filename = File.absolute_path( get_image_filename( sha256 )  )
    FileUtils.mv( uploaded_filename, stored_filename )

    #file the photo 
    pp = nil
    if photo_type == 1
      pp = PrimaryPhoto.create( item: self,
                               filename: "#{sha256}.jpg" )
    elsif photo_type == 2
      pp = SecondaryPhoto.create( item: self,
                               filename: "#{sha256}.jpg" )
    elsif photo_type == 3
      pp = InvoicePhoto.create( item: self,
                               filename: "#{sha256}.jpg" )
    else
      pp = ItemPhoto.create( item: self,
                               filename: "#{sha256}.jpg" )
    end

    pp.save

    return stored_filename

  end

  def remove_photo_file( photo_type = 1 )
    target = nil
    case photo_type
    when 1
      target = self.primary_photo
    when 2
      target = self.secondary_photo
    when 3
      target = self.invoice_photo
    end

    target.destroy if target
    #actually the file is not removed for tracing reasons

  end

end

inventory/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy,
                                  :picture, :picture_thumb, 
                                  :second_picture, :invoice]

  before_action :check_can_add, only: [:new, :create]
  before_action :check_can_edit, only:[:edit, :update, :destroy]

  skip_before_action :authorize, only:[:show, :picture, 
                                       :picture_thumb, :second_picture, 
                                       :invoice, :not_found]

  Thumbs_Directory = File.join( Rails.root, "thumbnails" )
  Photos_Directory = File.join( Rails.root, "item_photos" )

  #
  # Nothing is deleted.
  # Just burned.
  #
  def destroyed
    @items = Item.where( burned: true ).order(:serial)
    render :index
  end

  # GET /items
  # GET /items.json
  def index
    if not session[:show_mine]
      @items = Item.where( burned: false).order(:serial)
    else
      @items = Item.where( user_id: session[:user_id], burned: false ).order(:serial)
    end
    return @items
  end

  def toggle_show_all_mine
    if not session[:show_mine]
      session[:show_mine] = true
    else
      session[:show_mine] = false
    end
    redirect_to items_url
  end

  def not_found
    raise "Not found" #TODO
  end

  # GET /items/1
  # GET /items/1.json
  def show
    if not @item
      redirect_to action: :not_found
    end
  end

  def picture
    return if not @item.primary_photo
    ppfilename = photo_full_path( @item.primary_photo )

    send_file(ppfilename,
              filename: "#{@item.serial}.jpeg",
              type: "image/jpeg",
              disposition: "inline")
  end

  def remove_picture_thumb
    return if not @item.primary_photo
    filename = thumb_full_path( @item.primary_photo )
    begin
      FileUtils.rm filename
    rescue 
    end
  end

  def picture_thumb
    pphoto = @item.primary_photo
    return if not pphoto

    filename = thumb_full_path( pphoto ) 

    if not File.exist?(filename)
      FileUtils.mkdir(Thumbs_Directory) if not File.exist?(Thumbs_Directory)

      `convert #{File.join(Photos_Directory,pphoto.filename)} -resize 320 #{filename}`
    end

    send_file(filename)
  end

  def second_picture
    sphoto = @item.secondary_photo
    filename = "#{@item.serial}-2.jpeg" #maybe not needed?
    if params[:photo_id]
      sphoto = ItemPhoto.find(params[:photo_id])
    end

    return if not sphoto
    filename = sphoto.filename
    
    send_file(photo_full_path( sphoto ),
              filename: filename,
              type: "image/jpeg",
              disposition: "inline")
  end

  def invoice
    iphoto = @item.invoice_photo
    return if not iphoto

    send_file(photo_full_path( iphoto ),
              filename: "#{@item.serial}-invoice.jpg",
              type: "image/jpg",
              disposition: "inline")
  end

  # GET /items/new
  def new
    @item = Item.new
    #set who is creating
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create

    # 
    # ! item_params cannot be altered !
    #
    # Trying to delete an attribute will simply not happen (silently).
    # That's because item_params is a call to a method returning a value...
    #
    processed_params = item_params

    #following parameters are not used upon creation
    processed_params.delete :remove_photo
    processed_params.delete :remove_second_photo
    processed_params.delete :remove_invoice

    @item = Item.new(processed_params)
    @item.user_id = session[:user_id]
    @item.container_serial= params[:container_serial]

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    previous_container = @item.container
    @item.container_serial= params[:container_serial]
    if previous_container != @item.container
        #this is a movement  from container to @container
        #Log this movement
        movement = ItemMovement.create( user_id: session[:user_id],
                                       item_id: @item.id,
                                       container_id: previous_container ? previous_container.id : nil )
        movement.save
    end

    processed_params = item_params

    if processed_params[:remove_photo] == "1"
      processed_params.merge!( uploaded_picture: nil )
      puts "removing photo"
    end
    if processed_params[:remove_second_photo] == "1"
      processed_params.merge!( uploaded_second_picture: nil )
    end
    if processed_params[:remove_invoice] == "1"
      processed_params.merge!( uploaded_invoice: nil )
    end

    #we don't need them any more:
    processed_params.delete :remove_photo
    processed_params.delete :remove_second_photo
    processed_params.delete :remove_invoice

    remove_picture_thumb

    create_item_edits(@item, processed_params)

    respond_to do |format|
      if @item.update( processed_params )
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy

    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /upload_photo
  def upload_photo
  end

  #POST /upload_photo
  #Code is heavily duplicated here and in item.rb
  def search_and_place_photo
    serial_no = detect_single_serial_number(params[:uploaded_picture])
    raise "QR-code not readable." if not serial_no
    serial_no.strip!
    raise "QR-code not readable (2)." if serial_no==""
 
    item = Item.find_by( serial: serial_no )
    if item == nil 
      if not params[:create_entry]
        redirect_to(action: not_found)
        return
      elsif params[:create_entry] == "true"
        item = Item.create( serial: serial_no, user_id: session[:user_id] )
        item.save
      end
    end

    puts "Found item #{item.serial} that matches the scanned qr code."

    @item = item
    if not @item.primary_photo
      @item.update( uploaded_picture: params[:uploaded_picture] )
      redirect_to( @item ) and return
    end

    if not @item.secondary_photo
      @item.update( uploaded_second_picture: params[:uploaded_picture] )
      redirect_to( @item ) and return
    end

    #TODO : Allow more pictures, just do not tag them as primary or secondary
    #raise "Item #{item.serial}: Both photos have been uploaded. Remove a photo to upload a new one."

    @item.update( uploaded_second_picture: params[:uploaded_picture] )
    redirect_to( @item ) and return

  end

  # GET /upload_invoice
  def upload_invoice
  end

  #POST /upload_invoice
  #Code is heavily duplicated here and in item.rb
  def search_and_place_invoice
    uploaded_invoice = params[:uploaded_invoice]
    #Keep the uploaded filename
    uploaded_filename = File.absolute_path( uploaded_invoice.tempfile )
    puts "Uploaded invoice filename is #{uploaded_filename}"

    serials = detect_all_serial_numbers( uploaded_invoice )
    raise "QR-code not readable." if not serials
    raise "QR-code not readable." if serials.length == 0
    serials.each do |serial_no|
      serial_no.strip!
    end

    @results=[]
    previous_filename = uploaded_filename
    serials.each do |serial_no|
      item = Item.find_by( serial: serial_no )
      if item == nil
        @results << "item #{serial_no} not found"
        next
      end

      puts "Found item #{item.serial} that matches the scanned qr code."

      @item = item
      if not @item.invoice_photo
        #Copy the file to its uploaded location for the update
        if previous_filename != uploaded_filename
          puts previous_filename
          puts uploaded_filename
          FileUtils.cp( previous_filename, uploaded_filename )
        end

        #update will move the file, to internal storage
        @item.update( uploaded_invoice: uploaded_invoice )
        @item.save
        @item = Item.find_by( serial: serial_no )
        @results << "#{serial_no} OK"

        #For the next one to find the file
        previous_filename = @item.uploaded_invoice_full_path
        puts "Invoice filed with the name : #{previous_filename}"
      else
        @results << "Item #{serial_no} already has an invoice."
      end
    end
  end

  private

  def photo_full_path( photo_item ) 
    File.join(Photos_Directory, photo_item.filename)
  end
  def thumb_full_path( photo_item ) 
    File.join(Thumbs_Directory,photo_item.thumbnail_filename)
  end

    def create_item_edits(i, p)
      p.each do |k,v|
        old_v = i.send(k)
        new_v = v
        if k.include?("uploaded") and v!=nil
          #it's an image
          sha256 = i.calc_sha256( v.tempfile )
          new_v = i.get_base_filename( sha256 )
        end

        if new_v.to_s != old_v.to_s
          #it's some other field
          item_edit = ItemEdit.new( item_id: i.id,
                                   field_name: k, old_value: old_v, 
                                   new_value: new_v,
                                   user_id: session[:user_id])
          item_edit.save

        end
      end
    end

    def detect_single_serial_number(source)
      all_serials = detect_all_serial_numbers(source)
      if all_serials.length > 1
        #two codes found, user has to input the code manually
        puts "More than one code detected in the photo. User should type the right code manually"

inventory/app/helpers/items_helper.rb
module ItemsHelper
end

inventory/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :serial %>
    <%= form.text_field :serial, id: :item_serial %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :item_category_id, 
    ItemCategory.order(:category), :id, :category, 
    include_blank: true, prompt:true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :item_quantity %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note, id: :item_note, cols: 20, rows: 5 %>
  </div>

  <div class="field">
    <%= form.label :page_url %>
    <%= form.text_field :page_url, id: :item_page_url %>
  </div>

  <div class="field">
    <%= form.label "Inside" %>
    <table>
      <tr>
        <td>
          <% if @item.container %>
            <%= text_field_tag :container_serial, @item.container.serial %>
          <% else %>
            <%= text_field_tag :container_serial %>
          <% end %>
        </td>
        <td>
          Use "none" to empty this field
        </td>
      </tr>
    </table>
  </div>

  <div class="field">
    <%= form.label "Main photo with qr code" %>
    <p>
    <% if @item.primary_photo %>
      <br>
      <a target="_blank" href=<%= url_for(action: :picture, id: @item.id ) %>>
        <img width=320 src=<%= url_for(action: :picture_thumb, id: @item.id ) %> />
      </a>
    <% else %>
      none
    <% end %>
    </p>
    <%= form.file_field(:uploaded_picture, accept: "image/jpg") %> 
    <%= form.label "Remove photo" %>
    <%= form.check_box :remove_photo %>
  </div>

  <div class="field">
    <%= form.label "Second photo" %>
    <%= form.file_field(:uploaded_second_picture, accept: "image/jpg") %> 
    <%= form.label "Remove second photo" %>
    <%= form.check_box :remove_second_photo %>
  </div>

  <div class="field">
    <%= form.label "Invoice jpg" %>
    <%= form.file_field(:uploaded_invoice, accept: "image/jpg") %> 
    <%= form.label "Remove invoice" %>
    <%= form.check_box :remove_invoice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

inventory/app/views/items/edit.html.erb
<h1><%= session[:username] %> is editing an item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

inventory/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<% logged_user = User.find(session[:user_id]) %>

<h1>Items</h1>
<h3>
  <% if not session[:show_mine] %>
    Showing all. 
    <%= link_to 'Click to show yours.', toggle_show_all_mine_path %>
  <% else %>
    Showing only items created by you. 
    <%= link_to 'Click to show all.', toggle_show_all_mine_path %>
  <% end %>
</h3>

<table width="100%">
  <tr>
    <td align=left>
      <h3><%= link_to 'New Item', new_item_path %></h3>
    </td>
    <td align=right>
      <h3><%= link_to 'Auto file a photo', upload_photo_path %></h3>
      <h3><%= link_to 'Auto file an invoice', upload_invoice_path %></h3>
    </td>
  </tr>
</table>

<% if not @items %>
  <p> No items to show.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Serial</th>
        <th>Category</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Page URL</th>
        <th>Inside</th>
        <th>Created by</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.serial, item %></td>
          <td><%= link_to item.item_category ? item.item_category.category : "", item %> </td>
          <td><%= link_to item.description, item %></td>
          <td><%= item.quantity %></td>
          <% if item.page_url and item.page_url!='' %>
            <td><a href="<%= item.page_url %>">Περισσότερα</a></td>
          <% else %>
            <td></td>
          <% end %>
          <td align=center ><%= item.container.nil? ? "":item.container.serial %></td>
          <td align=center ><%= item.user.nil? ? "":item.user.username %></td>
          <% if logged_user.can_edit? or session[:user_id] == item.user_id %>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td> ------------- </td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td></td>
            <td></td>
            <td></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<br>

<table width="100%">
  <tr>
    <td align=left>
      <h3><%= link_to 'New Item', new_item_path %></h3>
    </td>
    <td align=right>
      <h3><%= link_to 'Auto file a photo', upload_photo_path %></h3>
    </td>
  </tr>
</table>

inventory/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

inventory/app/views/items/not_found.html.erb
<p> Item not found </p>
<%= link_to 'Back', items_path %>

inventory/app/views/items/search_and_place_invoice.html.erb
<% logged_user = User.find(session[:user_id]) %>
<h1> Results of auto-uploading invoice </h1>
<ul>
<% @results.each do |result| %>
  <li>
    <%= result %>
  </li>
<% end %>
</ul>
<p>
<%= @results.length %> qr-codes were detected.
</p>

inventory/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<table border=1>
  <tr>
    <td>
      <p><small><%=@item.id%></small></p>
      <p>
      <strong>Serial:</strong> 
      <%= @item.serial %>
      created by <%= @item.user ? @item.user.username : "UNDEF" %> <br>
      Last edited by <%= ItemMovementsController::last_editor(@item) %>
    </p>
    </td>
    <td>Contents of this item</td>
  </tr>
  <tr>
    <td>

    <p>
    <strong>Category:</strong>
    <%= @item.item_category.category if @item.item_category %>
    </p>

    <p>
    <strong>Description:</strong>
    <%= @item.description %>
    </p>

    <p>
    <strong>Quantity:</strong>
    <%= @item.quantity %>
    </p>

    <p>
    <strong>Notes:</strong>
    <%= @item.note %>
    </p>

    <p>
    <strong>Page URL:</strong>
    <% if @item.page_url %>
      <a href=<%= @item.page_url %>><%= @item.page_url %></a>
    <% else %>
      none
    <% end %>
    </p>

    <p>
    <strong>Photo:</strong>
    <% if @item.primary_photo %>
      <br>
      <a target="_blank" href=<%= url_for(action: :picture, id: @item.id ) %>>
        <img width=320 src=<%= url_for(action: :picture_thumb, id: @item.id ) %> />
      </a>
    <% else %>
      none
    <% end %>
    </p>

    <p>
    <strong>Second photo:</strong>
    <% if @item.secondary_photo %>
      <br>
      <a target="_blank" href=<%= url_for(action: :second_picture, id: @item.id) %> >
        click for the second picture
      </a>
    <% else %>
      none
    <% end %>
    </p>

    <strong>all other photos:</strong>
    <% @item.other_photos.each do |photo_id| %>
	      <br>
	      <a target="_blank" href=<%= url_for(action: :second_picture, id: @item.id, photo_id: photo_id) %> >
		click for another picture
	      </a>
    <% end %>
    </p>

    <p>
    <strong>Invoice:</strong>
    <% if @item.invoice_photo %>
      <a target="_blank" href=<%= url_for(action: :invoice, id: @item.id) %> >JPG</a>
    <% else %>
      none
    <% end %>
    </p>

    <p>
    <strong>Current Container : </strong>
    <% if @item.container.nil? %>
      none
    <% else %>
      <%= link_to "#{@item.container.serial} ( #{@item.container.description})", @item.container %>
    <% end %>
    <br>
    </p>
    </td>
    <td>
      <ul>
      <% @item.get_immediate_contents.each do |item| %>
        <li> <%= link_to "#{item.serial} #{item.description}", item %></li>
      <% end %>
      </ul>
    </td>
  </tr>
</table>


<p>
<%= link_to ' history of movements for this item', movements_path(id: @item.id) %>
<br>
<%= link_to "history of edits for this item", edits_path(id: @item.id) %> 
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

inventory/app/views/items/upload_invoice.html.erb
<%= form_tag( '/upload_invoice', multipart: true ) do  %>
  <div class="field">
    <%= label_tag "Photo of invoice with qr code" %>
    <%= file_field_tag  :uploaded_invoice, accept: "image/jpg"  %> 
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

inventory/app/views/items/upload_photo.html.erb
<%= form_tag( '/upload_photo', multipart: true ) do  %>
  <p>
  </p>

  <div class="field">
  </div>

  <div class="field">
    <table>
      <tr>
        <td><%= label_tag "Photo with qr code" %></td>
        <td><%= file_field_tag  :uploaded_picture, accept: "image/jpg"  %> </td>
      </tr>
      <tr>
        <td><%= label_tag "Create item entry if it doesn't exist." %></td>
        <td><%= check_box_tag  "create_entry", true  %> </td>
      </tr>
    </table>
  </div>

  <div class="actions">
    <%= submit_tag 'Start Uploading' %>
  </div>
<% end %>