inventory/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy 
  end

  resources :users
  resources :items
  resources :item_categories
  resources :item_edits #TODO : To remove

  get '/', to: 'items#index'
  get '/destroyed', to: 'items#destroyed'
  get '/KT/:serial', to:'items#show' #KT in english letters
  get '/RM/:serial', to:'items#show' #Rooms
  get '/I/:serial', to:'items#show' #I english letters Items
  get '/VP/:serial', to:'items#show' #I english letters Virtual Places

  get 'not_found', to: 'items#not_found'
  get 'picture', to: 'items#picture'
  get 'picture_thumb', to: 'items#picture_thumb'
  get 'second_picture', to: 'items#second_picture'
  get 'invoice', to: 'items#invoice'

  get '/upload_photo', to: 'items#upload_photo'
  post '/upload_photo', to: 'items#search_and_place_photo'

  get '/upload_invoice', to: 'items#upload_invoice'
  post '/upload_invoice', to: 'items#search_and_place_invoice'

  get '/toggle_show_all_mine', to: 'items#toggle_show_all_mine'

  get '/movements/:id', to: 'item_movements#index', as: "movements"

  get '/edits/:id', to: 'item_edits#index', as: "edits"

  get '/categories', to: 'item_categories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
 

  #----- Temporarily enabled for debugging : ( TODO )
  resources :item_photos
  resources :primary_photos
  resources :secondary_photos
  resources :invoice_photos
  #----------

end

inventory/app/models/secondary_photo.rb
class SecondaryPhoto < ItemPhoto
end

inventory/app/controllers/secondary_photos_controller.rb
class SecondaryPhotosController < ApplicationController
  before_action :set_secondary_photo, only: [:show, :edit, :update, :destroy]

  # GET /secondary_photos
  # GET /secondary_photos.json
  def index
    @secondary_photos = SecondaryPhoto.all
  end

  # GET /secondary_photos/1
  # GET /secondary_photos/1.json
  def show
  end

  # GET /secondary_photos/new
  def new
    @secondary_photo = SecondaryPhoto.new
  end

  # GET /secondary_photos/1/edit
  def edit
  end

  # POST /secondary_photos
  # POST /secondary_photos.json
  def create
    @secondary_photo = SecondaryPhoto.new(secondary_photo_params)

    respond_to do |format|
      if @secondary_photo.save
        format.html { redirect_to @secondary_photo, notice: 'Secondary photo was successfully created.' }
        format.json { render :show, status: :created, location: @secondary_photo }
      else
        format.html { render :new }
        format.json { render json: @secondary_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondary_photos/1
  # PATCH/PUT /secondary_photos/1.json
  def update
    respond_to do |format|
      if @secondary_photo.update(secondary_photo_params)
        format.html { redirect_to @secondary_photo, notice: 'Secondary photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @secondary_photo }
      else
        format.html { render :edit }
        format.json { render json: @secondary_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondary_photos/1
  # DELETE /secondary_photos/1.json
  def destroy
    @secondary_photo.destroy
    respond_to do |format|
      format.html { redirect_to secondary_photos_url, notice: 'Secondary photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondary_photo
      @secondary_photo = SecondaryPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secondary_photo_params
      params.fetch(:secondary_photo, {})
    end
end

inventory/app/helpers/secondary_photos_helper.rb
module SecondaryPhotosHelper
end

inventory/app/views/secondary_photos/_form.html.erb
<%= form_with(model: secondary_photo, local: true) do |form| %>
  <% if secondary_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secondary_photo.errors.count, "error") %> prohibited this secondary_photo from being saved:</h2>

      <ul>
      <% secondary_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

inventory/app/views/secondary_photos/edit.html.erb
<h1>Editing Secondary Photo</h1>

<%= render 'form', secondary_photo: @secondary_photo %>

<%= link_to 'Show', @secondary_photo %> |
<%= link_to 'Back', secondary_photos_path %>

inventory/app/views/secondary_photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Secondary Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @secondary_photos.each do |secondary_photo| %>
      <tr>
        <td><%= link_to 'Show', secondary_photo %></td>
        <td><%= link_to 'Edit', edit_secondary_photo_path(secondary_photo) %></td>
        <td><%= link_to 'Destroy', secondary_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Secondary Photo', new_secondary_photo_path %>

inventory/app/views/secondary_photos/new.html.erb
<h1>New Secondary Photo</h1>

<%= render 'form', secondary_photo: @secondary_photo %>

<%= link_to 'Back', secondary_photos_path %>

inventory/app/views/secondary_photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_secondary_photo_path(@secondary_photo) %> |
<%= link_to 'Back', secondary_photos_path %>