inventory/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy 
  end

  resources :users
  resources :items
  resources :item_categories
  resources :item_edits #TODO : To remove

  get '/', to: 'items#index'
  get '/destroyed', to: 'items#destroyed'
  get '/KT/:serial', to:'items#show' #KT in english letters
  get '/RM/:serial', to:'items#show' #Rooms
  get '/I/:serial', to:'items#show' #I english letters Items
  get '/VP/:serial', to:'items#show' #I english letters Virtual Places

  get 'not_found', to: 'items#not_found'
  get 'picture', to: 'items#picture'
  get 'picture_thumb', to: 'items#picture_thumb'
  get 'second_picture', to: 'items#second_picture'
  get 'invoice', to: 'items#invoice'

  get '/upload_photo', to: 'items#upload_photo'
  post '/upload_photo', to: 'items#search_and_place_photo'

  get '/upload_invoice', to: 'items#upload_invoice'
  post '/upload_invoice', to: 'items#search_and_place_invoice'

  get '/toggle_show_all_mine', to: 'items#toggle_show_all_mine'

  get '/movements/:id', to: 'item_movements#index', as: "movements"

  get '/edits/:id', to: 'item_edits#index', as: "edits"

  get '/categories', to: 'item_categories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
 

  #----- Temporarily enabled for debugging : ( TODO )
  resources :item_photos
  resources :primary_photos
  resources :secondary_photos
  resources :invoice_photos
  #----------

end

inventory/app/models/item_category.rb
class ItemCategory < ApplicationRecord
end

inventory/app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :set_item_category, only: [:show, :edit, :update]

  def index
    @item_categories = ItemCategory.all.order(:category)
  end
 


  # GET /item_categories/new
  def new
    @item_category = ItemCategory.new
  end

  # GET /item_categories/1/edit
  def edit
  end

  # PATCH/PUT /items/1
  def update
    respond_to do |format|
      if @item_category.update(item_category_params)
        format.html { redirect_to @item_category, notice: 'Item category was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_category }
      else
        format.html { render :edit }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /item_categories
  def create
    @item_category = ItemCategory.new(item_category_params)

    respond_to do |format|
      if @item_category.save
        format.html { redirect_to @item_category, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item_category }
      else
        format.html { render :new }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /items/1
  def show
  end
 
  private 

    def set_item_category
      @item_category = ItemCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, 
    # only allow the white list through.
    def item_category_params
      params.require(:item_category).permit(
                                   :category, 
                                   :description
                                  )
    end

end

inventory/app/views/item_categories/_form.html.erb
<%= form_with(model: item_category, local: true) do |form| %>
  <% if item_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_category.errors.count, "error") %> prohibited this item_category from being saved:</h2>

      <ul>
      <% item_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category_category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :item_category_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

inventory/app/views/item_categories/edit.html.erb
<h1>Editing item category</h1>

<%= render 'form', item_category: @item_category %>

<%= link_to 'Show', @item_category %> |
<%= link_to 'Back', item_categories_path %>

inventory/app/views/item_categories/index.html.erb
<p id="notice"><%= notice %></p>

<p>
Logged in as <%= session[:username] %>. 
<%= link_to 'Logout', logout_path, method: :delete %>
</p>

<h1>Item Categories</h1>

<%= link_to 'New Category', new_item_category_path %>

<% if not @item_categories %>
  <p> No categories to show.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Category</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @item_categories.each do |category| %>
        <tr>
          <td><%= category.category %></td>
          <td><%= category.description %></td>
          <td><%= link_to 'Edit', edit_item_category_path(category) %></td>
          <td> ------------- </td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<%= link_to 'New Category', new_item_category_path %>

inventory/app/views/item_categories/new.html.erb
<h1>New Item Category</h1>

<%= render 'form', item_category: @item_category %>

<%= link_to 'Back', item_categories_path %>

inventory/app/views/item_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @item_category.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item_category.description %>
</p>

<%= link_to 'Edit', edit_item_category_path(@item_category) %> |
<%= link_to 'Back', item_categories_path %>